## Todos los ejercicios tienen qué estar documentados en Python y comentados.

1. Se tienen las siguientes matrices:
\begin{split}
\begin{equation}
E = \left[ \begin{array}{r} 5 \\ -2 \end{array}\right] \hspace{1cm}
F = \left[ \begin{array}{rr} 1 & 6 \\ 2 & 0 \\ -1 & -1 \end{array}\right] \hspace{1cm}
G = \left[ \begin{array}{rr} 2 & 0\\ -1 & 3 \\ -1 & 6 \end{array}\right] \hspace{1cm}
H = \left[ \begin{array}{rrr} 3 & 0 & 1 \\ 1 & -2 & 2 \\ 3 & 4 & -1\end{array}\right]
\end{equation}
\end{split}

Calcula lo siguiente:

 $-5E$,$G+F$, $4F-G$, $HG$ y $GE$

---

2. Encuentra $x$ y $y$ tal que se cumpla:

\begin{split}
\begin{equation}
\left[ \begin{array}{rr} 1 & 3 \\ -4 & 2 \end{array}\right]
\left[ \begin{array}{rr} 3 & x \\ 2 & y \end{array}\right]=
\left[ \begin{array}{rr} 9 & 10 \\ -8 & 16 \end{array}\right]
\end{equation}
\end{split}

---


3. Genera una matriz de tamaño $3\times 4$ a partir de una lista de 12 enteros que se eligen al azar del conjunto $\{1,2,3,\dots, 100\}$. Usando las funciones  𝚁𝚘𝚠𝚂𝚠𝚊𝚙,𝚁𝚘𝚠𝚂𝚌𝚊𝚕𝚎 y 𝚁𝚘𝚠𝙰𝚍𝚍, reduce tal matriz.
---

4. Usando  𝚁𝚘𝚠𝚂𝚠𝚊𝚙,𝚁𝚘𝚠𝚂𝚌𝚊𝚕𝚎 y 𝚁𝚘𝚠𝙰𝚍𝚍; verifica que el sistema de ecuaciones

\begin{split}
\begin{eqnarray*}
x_1 - x_2 + x_3 & = & 3\\
2x_1 - 2x_2 + 4x_3 & = & 8\\
3x_1 -3x_2 +3x_3 & = & 9
\end{eqnarray*}
\end{split}

tiene solución no única.

---

5. Realice el proceso de eliminación en el siguiente sistema. Defina una matriz en NumPy y haga uso de las funciones de operación de fila. Imprime los resultados de cada paso. Escriba el sistema triangular superior representado por la matriz después de completar todos los pasos.

---

6. Usa la eliminación para determinar si el siguiente sistema es consistente o inconsistente.

\begin{split}
\begin{eqnarray*}
x_1 - x_2 - x_3 & = & 4\\
2x_1 - 2x_2 - 2x_3 & = & 8\\
5x_1 - 5x_2 - 5x_3 & = & 20
\end{eqnarray*}
\end{split}




---



In [ ]:
import numpy as np



In [ ]:
#1
E = np.array([[5],[-2]])
F = np.array([[1,6],[2,0],[-1,-1]])
G = np.array([[2, 0],[-1,3],[-1,6]])
H = np.array([[3, 0,1],[1,-2,2], [3,4,-1]])
minus_5E = -5 * E
sum_G_F = np.add(G, F)
diff_4F_G = np.subtract(4 * F, G)
HG = np.matmul(H,G )
GE = np.matmul(G, E)
print("-5E:")
print(minus_5E)
print("G + F:")
print(sum_G_F)
print("4F - G:")
print(diff_4F_G)
print("HG:")
print(HG)
print("GE:")
print(GE)

-5E:
[[-25]
 [ 10]]
G + F:
[[ 3  6]
 [ 1  3]
 [-2  5]]
4F - G:
[[  2  24]
 [  9  -3]
 [ -3 -10]]
HG:
[[5 6]
 [2 6]
 [3 6]]
GE:
[[ 10]
 [-11]
 [-17]]


In [ ]:
#2
import numpy as np


C = np.array([[9, 10], [-8, 16]])


A = np.array([[1, 3], [-4, 2]])


A_inv = np.linalg.inv(A)


B = np.dot(A_inv, C)


x = B[0, 1]
y = B[1, 1]


print("x =", x)
print("y =", y)

x = -2.0000000000000004
y = 3.9999999999999996


In [ ]:
#3
import numpy as np


lista_enteros = np.random.choice(np.arange(1, 101), size=12, replace=False)


matriz = np.reshape(lista_enteros, (3, 4))

print("Matriz original:")
print(matriz)
def row_swap(matrix, row1, row2):
    matrix[[row1, row2]] = matrix[[row2, row1]]

def row_scale(matrix, row, scalar):
    matrix[row] *= scalar


def row_add(matrix, row1, row2, scalar):
    matrix[row1] += scalar * matrix[row2]




for i in range(len(matriz)):

    if matriz[i, i] == 0:
        for j in range(i+1, len(matriz)):
            if matriz[j, i] != 0:
                matriz[[i, j]] = matriz[[j, i]]
                break

    matriz[i] = matriz[i] / matriz[i, i]

    for j in range(len(matriz)):
        if i != j:
            matriz[j] = matriz[j] - matriz[j, i] * matriz[i]

print("Matriz reducida:")
print(matriz)

Matriz original:
[[59 63 82 81]
 [16 60 17 70]
 [30 99  4 87]]
Matriz reducida:
[[1 0 0 0]
 [0 1 0 1]
 [0 0 1 0]]


In [ ]:
#4
import numpy as np


A = np.array([[1, -1, 3, 3],
              [2, -2, 4, 8],
              [3, -3, 3, 9]])


for i in range(len(A)):

    if A[i, i] == 0:
        for j in range(i+1, len(A)):
            if A[j, i] != 0:
                A[[i, j]] = A[[j, i]]
                break

    A[i] = A[i] / A[i, i]

    for j in range(len(A)):
        if i != j:
            A[j] = A[j] - A[j, i] * A[i]


rank = np.linalg.matrix_rank(A[:, :-1])
if rank < len(A):
    print("El sistema tiene solución no única.")
else:
    print("El sistema tiene solución única.")

El sistema tiene solución no única.


<ipython-input-35-0213d3652ae9>:17: RuntimeWarning: divide by zero encountered in true_divide
  A[i] = A[i] / A[i, i]
<ipython-input-35-0213d3652ae9>:17: RuntimeWarning: invalid value encountered in true_divide
  A[i] = A[i] / A[i, i]


In [ ]:
#5
import numpy as np


matriz = np.random.rand(3, 3)
print("Matriz original:")
print(matriz)


factor = matriz[1, 0] / matriz[0, 0]
matriz[1, :] -= factor * matriz[0, :]
print("Paso 1:")
print(matriz)

factor = matriz[2, 0] / matriz[0, 0]
matriz[2, :] -= factor * matriz[0, :]
print("Paso 2:")
print(matriz)


factor = matriz[2, 1] / matriz[1, 1]
matriz[2, :] -= factor * matriz[1, :]
print("Paso 3:")
print(matriz)


print("Matriz triangular superior:")
print(matriz)

Matriz original:
[[0.30766751 0.03555071 0.94961281]
 [0.59864433 0.86594692 0.82147539]
 [0.6528318  0.98986336 0.45601214]]
Paso 1:
[[ 0.30766751  0.03555071  0.94961281]
 [ 0.          0.7967741  -1.02623457]
 [ 0.6528318   0.98986336  0.45601214]]
Paso 2:
[[ 0.30766751  0.03555071  0.94961281]
 [ 0.          0.7967741  -1.02623457]
 [ 0.          0.91442923 -1.55894691]]
Paso 3:
[[ 3.07667511e-01  3.55507069e-02  9.49612806e-01]
 [ 0.00000000e+00  7.96774102e-01 -1.02623457e+00]
 [ 0.00000000e+00 -1.11022302e-16 -3.81174088e-01]]
Matriz triangular superior:
[[ 3.07667511e-01  3.55507069e-02  9.49612806e-01]
 [ 0.00000000e+00  7.96774102e-01 -1.02623457e+00]
 [ 0.00000000e+00 -1.11022302e-16 -3.81174088e-01]]


In [ ]:
#6
import numpy as np


A = np.array([[1, -1, -1, 4],
              [2, -2, -2, 8],
              [5, -5, -5, 20]])


for i in range(len(A)):
    pivot = A[i, i]
    for j in range(i + 1, len(A)):
        ratio = A[j, i] / pivot
        A[j] = A[j] - ratio * A[i]


last_row = A[-1]
zeros = np.count_nonzero(last_row[:-1])
if zeros == 0 and last_row[-1] != 0:
    print("El sistema es inconsistente.")
elif zeros == 0 and last_row[-1] == 0:
    print("El sistema tiene infinitas soluciones.")
else:
    print("El sistema es consistente.")

El sistema es consistente.


<ipython-input-40-b3d1820b0534>:13: RuntimeWarning: invalid value encountered in long_scalars
  ratio = A[j, i] / pivot
